security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        my_profile_db:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            user_checker: App\Security\UserChecker
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                username_parameter: login_form[_username]
                password_parameter: login_form[_password]
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back-office, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
