name: Test SSH Connection
on:
  workflow_dispatch:

jobs:
  ssh_connection:
    runs-on: ubuntu-latest
    steps:
      - name: test appleboy test-ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: whoami